version: "3.3"
services:
    backend:
      build: ./backend
      ports:
        - 8000:5000
    frontend:
      build: ./frontend/cuisine-app
      container_name: frontend
      restart: always
      ports:
          - 4200:4200
      expose:
          - "4200"


